engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      complexity:
        enabled: true
    # ... CONFIG CONTENT ...
    checks:
      comma-dangle:
        enabled: false
# ... CONFIG CONTENT ...