build: off

os: unstable

platform:
  - x86
  - x64

branches:
  only:
    - master

skip_tags: true

environment:
  nodejs_version: "6.7.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - .\node_modules\.bin\npm install

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  - npm test
  - npm run release
  
  
artifacts:
  - path: dist/*.exe
    name: Installer

deploy:
  release: electron-wf-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 16gK17SsYWLCBRxeDTZbTFAvu+38JModzNSC0F8gZBI1xcbchnwFJ//gWIo4HlTO # your encrypted token from GitHub
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: false        # deploy on tag push only